module.exports = {
    userController: require('./controllers/userController'),
    marketsController: require('./controllers/marketsController'),
    matchesController: require('./controllers/matchesController'),
    seriesController: require('./controllers/seriesController'),
    sportsController: require('./controllers/sportsController'),
    fancyController: require('./controllers/fancyController'),
    accountStatementsController: require('./controllers/accountStatementsController'),
    globalSettingController: require('./controllers/globalSettingController'),
    betsController: require('./controllers/betsController'),
    userSettingController: require('./controllers/userSettingController'),
    exchangeController: require('./controllers/exchangeController'),
    reportController: require('./controllers/reportController'),
    scoreController: require('./controllers/scoreController'),
    notificationsController: require('./controllers/notificationsController'),
    apkController: require('./controllers/apkController'),
    subAdminRolesController: require('./controllers/subAdminRolesController'),
    subAdminController: require('./controllers/subAdminController'),
    resultController: require('./controllers/resultController'),
    virtualGameApiController: require('./controllers/virtualGameApiController'),
    casinoGamesReportController: require('./controllers/casinoGamesReportController'),
    paymentApiController: require('./controllers/paymentApiController'),
};